name = "random-gif-preview"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".svelte-kit/cloudflare"

# Uncomment if you want to use a custom domain
# routes = [
#   { pattern = "yourdomain.com", custom_domain = true }
# ]
